### ISSUE TITLE
Implement UEX

### ISSUE THREAD

**Issue by wongy91** [coingecko/cryptoexchange#1000]
https://github.com/UEX-OpenAPI/API_Docs/wiki

**Comment by yihyang** [comment]
I will take this

**Comment by tmlee** [comment]
Awesome, thanks!

**Comment by yihyang** [comment]
@tmlee here you go: https://github.com/coingecko/cryptoexchange/pull/1001

I'm a bit unclear about the
-**(If implementing Market Ticker) I have verified that the `volume` refers to BASE**

Please help me verify. Thanks.

**Comment by tmlee** [comment]
@yihyang to clarify, here is an example

Assume the pair is ETH/USDT
you would map
base = ETH
target = USDT
volume <--- this volume should be in the denomination of base (ETH) in this case

Sometimes you can tell by looking at the number. eg. if its base is BTC, the number is usually small because BTC is highly valuable against the opposing currency typically

But if in doubt you can always cross check with the exchange website.

For this case i cross check with https://www.uex.com/trade and it says ETH/USDT volume is 18694 ETH and that number corresponds with vol in the API, as such we can just go ahead and assign that

**Comment by yihyang** [comment]
@tmlee meaning the PR is ready to be merged?
