### ISSUE TITLE
Implement Bitinka Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#757]
https://www.bitinka.com.ar/

**Comment by nomanurrehman** [comment]
I am working on this one.

**Comment by nomanurrehman** [comment]
Can someone explain what is volumen and volumen24 at https://www.bitinka.com/uk/bitinka/api_documentation ?

**Comment by estherleongym** [comment]
hey @nomanurrehman sorry for the late response:

**Comment by nomanurrehman** [comment]
@estherleongym 

Unfortunately, both answers do not answer my question.

1. I actually wanted to know what these endpoints return? Ticker? Order book? Since it is not obvious from the name.

2. Yes but how does one come to know the pairs supported by an exchange since there is no endpoint?

**Comment by estherleongym** [comment]
@nomanurrehman 

For 1, because we don't own this exchange, none of us would be able to tell for sure so to minimize doubt, it'd be best to reach out to the team via the communication channels they have available. This is normal practice; we reach out to the team if we have questions or would like to check if they have more information than is documented.

For 2, this will take eyeballing from the main exchange site because of the very reason you cited - there is no endpoint to provide pairs.

**Comment by bobbyong** [comment]
@estherleongym if you are free, do kindly take over this exchange. thank you

**Comment by estherleongym** [comment]
@bobbyong ok, sure!
